import { shareInvoiceFile } from "./sharer";

function escapeHtml(text: string): string {
 return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

export async function shareDataAsPdf(
 title: string,
 headers: string[],
 rows: (string | number | null | undefined)[][],
 filename = "export.pdf",
): Promise<void> {
 const html = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>
 body { font-family: sans-serif; padding: 24px; }
 h2 { margin-bottom: 16px; color: #333; }
 table { width: 100%; border-collapse: collapse; font-size: 12px; }
 th { background: #0368FE; color: white; padding: 8px 10px; text-align: left; }
 td { padding: 6px 10px; border-bottom: 1px solid #e5e7eb; }
 tr:nth-child(even) td { background: #f9fafb; }
 .footer { margin-top: 20px; font-size: 10px; color: #9ca3af; text-align: center; }
</style></head>
<body>
 <h2>${escapeHtml(title)}</h2>
 <table><thead><tr>${headers.map((h) => `<th>${escapeHtml(h)}</th>`).join("")}</tr></thead>
 <tbody>${rows.map((row) => `<tr>${row.map((cell) => `<td>${cell == null ? "—" : escapeHtml(String(cell))}</td>`).join("")}</tr>`).join("")}</tbody>
 </table>
 <div class="footer">Generated by MMC User App</div>
</body></html>`;
 await shareInvoiceFile(html, filename);
}
