/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "media", // system-following; RN has no "class" toggle mechanism like the web export
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      // Stitch ERP design system (D:\Projects\Shopk\stitch_responsive_app_design)
      // — token names match the exported HTML 1:1 so screen markup can be
      // ported over with minimal class-name translation.
      // Brand palette (managemycounter, all products): #004CFA deep blue,
      // #0368FE bright blue (primary), #000D3A navy, #03A8FE cyan-blue
      // (dark-mode primary / accent). Every "primary"-family M3 token below
      // was previously a teal/green (#005f49-ish) — remapped to blue,
      // preserving each token's original light/dark relationship.
      colors: {
        "tertiary-container": "#a5544a",
        "on-tertiary-container": "#ffe9e6",
        "secondary-dark": "#F0AE4E",
        "secondary-fixed": "#ffddb5",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#3d0604",
        "inverse-surface": "#313030",
        "on-secondary-fixed": "#2a1800",
        success: "#2E9E5B",
        "surface-dark": "#1F1F1F",
        background: "#fcf9f8",
        "inverse-primary": "#03A8FE",
        "secondary-container": "#feb64e",
        "surface-container-highest": "#e5e2e1",
        "on-error": "#ffffff",
        "surface-tint": "#0368FE",
        info: "#0368FE",
        "text-secondary-dark": "#A0A0A0",
        "inverse-on-surface": "#f3f0ef",
        "tertiary-fixed-dim": "#ffb4aa",
        "on-error-container": "#93000a",
        surface: "#fcf9f8",
        "surface-container-low": "#f6f3f2",
        "on-primary-fixed-variant": "#000D3A",
        "surface-variant": "#e5e2e1",
        "on-surface": "#1c1b1b",
        "on-secondary": "#ffffff",
        "on-primary-container": "#d9e8ff",
        "on-surface-variant": "#3e4944",
        "on-secondary-fixed-variant": "#643f00",
        "primary-fixed-dim": "#03A8FE",
        "primary-dark": "#03A8FE",
        "on-tertiary-fixed-variant": "#773129",
        "surface-container-lowest": "#ffffff",
        primary: "#0368FE",
        "outline-variant": "#bdc9c2",
        "text-primary-dark": "#F2F2F2",
        "surface-bright": "#fcf9f8",
        outline: "#6e7a74",
        "surface-container": "#f0eded",
        secondary: "#835400",
        "on-primary-fixed": "#000D3A",
        "tertiary-fixed": "#ffdad5",
        "text-secondary-light": "#6B6B6B",
        "on-background": "#1c1b1b",
        "bg-dark": "#141414",
        "primary-container": "#004CFA",
        "surface-light": "#FFFFFF",
        "secondary-fixed-dim": "#ffb956",
        error: "#D64545",
        "on-secondary-container": "#714800",
        "surface-dim": "#dcd9d9",
        "on-primary": "#ffffff",
        "bg-light": "#FAF9F6",
        "primary-fixed": "#d9e8ff",
        "surface-container-high": "#eae7e7",
        tertiary: "#873d34",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        xl: "32px",
        lg: "24px",
        unit: "4px",
        "margin-tablet": "32px",
        md: "16px",
        gutter: "16px",
        xs: "4px",
        "touch-target": "44px",
        sm: "8px",
      },
      // Family names match what src/lib/fonts.ts registers via expo-font.
      // Only 2 real weights exist (Light 300, ExtraBold 800 — free tier),
      // so each token below picks whichever is closer to its fontSize
      // entry's intended fontWeight (see fontSize block just below):
      // ≥500 -> ExtraBold, ≤400 -> Light. RN has no CSS-style font-weight
      // matching within one family, unlike the web @font-face setup, so
      // this mapping has to be explicit here.
      fontFamily: {
        "headline-md": ["Gilroy-ExtraBold"],
        "body-lg": ["Gilroy-Light"],
        caption: ["Gilroy-Light"],
        "headline-lg": ["Gilroy-ExtraBold"],
        "numeric-emphasis": ["Gilroy-ExtraBold"],
        "headline-sm": ["Gilroy-ExtraBold"],
        "label-md": ["Gilroy-ExtraBold"],
        "display-lg": ["Gilroy-ExtraBold"],
        "body-md": ["Gilroy-Light"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        caption: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "numeric-emphasis": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" },
        ],
        "display-lg": [
          "40px",
          { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
